### ISSUE TITLE
Python is not compiled with SSL

### ISSUE THREAD

**Issue by mluszczyk** [derekkwok/homebrew-python#6]
I'm trying to install python 3.4. However, the installed interpreter seems to be compiled without openssl. This means that I can't use pip on it. Is there something I am doing wrong?

Way to reproduce:

```
brew uninstall python34

brew install --force openssl
brew install python34
which python3.4
python3.4 --version
python3.4 -c "import ssl"
```

The output:

```
+ brew uninstall python34
Error: No such keg: /usr/local/Cellar/python34
+ brew install --force openssl
Warning: openssl-1.0.2j already installed, it's just not linked.
+ brew install python34
==> Installing python34 from derekkwok/python
==> Downloading https://www.python.org/ftp/python/3.4.4/Python-3.4.4.tgz
Already downloaded: /Users/michal/Library/Caches/Homebrew/python34-3.4.4.tgz
==> ./configure --prefix=/usr/local/Cellar/python34/3.4.4 CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib
==> make
==> make install
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
is a symlink belonging to python. You can unlink it:
  brew unlink python

To force the link and overwrite all conflicting files:
  brew link --overwrite python34

To list all files that would be deleted:
  brew link --overwrite --dry-run python34

Possible conflicting files are:
/usr/local/bin/2to3 -> /usr/local/Cellar/python/2.7.13/bin/2to3
/usr/local/bin/idle3 -> /usr/local/Cellar/python3/3.6.0/bin/idle3
/usr/local/bin/pydoc3 -> /usr/local/Cellar/python3/3.6.0/bin/pydoc3
/usr/local/bin/python3 -> /usr/local/Cellar/python3/3.6.0/bin/python3
/usr/local/bin/python3-config -> /usr/local/Cellar/python3/3.6.0/bin/python3-config
/usr/local/bin/pyvenv -> /usr/local/Cellar/python3/3.6.0/bin/pyvenv
/usr/local/share/man/man1/python3.1 -> /usr/local/Cellar/python3/3.6.0/share/man/man1/python3.1
==> Summary
🍺  /usr/local/Cellar/python34/3.4.4: 4,919 files, 79.8M, built in 3 minutes 5 seconds
+ which python3.4
/usr/local/bin/python3.4
+ python3.4 --version
Python 3.4.4
+ python3.4 -c 'import ssl'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python34/3.4.4/lib/python3.4/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named '_ssl'
```

**Comment by derekkwok** [comment]
You'll need `brew install openssl` before installing python.

**Comment by danni** [comment]
Possibly related, but it also appears not to have support for zlib.

**Comment by M3t0r** [comment]
I had success with `LANG=C brew install --env=std python3{1,2,3,4}`.
